name = "Menoria Estival 2026"
author = "angiko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0eae52199651e7eb65f13cc63bcc078ae8579404164a0a34359797d2fb29458"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
