name = "Menoria Estival 2026"
author = "angiko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b8994e0acb6b2144dbc3ded0f7a5d10d3a6dbc47b87e081988661ae17bc4797"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
